name: Teste Runner

on:
  push:
    branches: [main]

jobs:
  teste:
    runs-on: self-hosted

    steps:
      - name: Confirmar que está a correr no runner
        run: |
          echo "Runner a funcionar!"
          hostname
          whoami

      - name: Confirmar Node.js
        run: node -v

      - name: Confirmar acesso à rede interna
        run: ping -c 3 10.0.0.2
